### PR TITLE
gh-249: Replace azure with cloud in _pystats.yml

### PR DESCRIPTION
**Pull request by yuqiw4**
In order to run _pystats job with other non-Azure self-hosted machine. 

Fixed https://github.com/faster-cpython/bench_runner/issues/249.

### CODE REVIEW

**Review by mdboom — CHANGES_REQUESTED** [review]
Can you also update the compare script to exclude these results?

https://github.com/faster-cpython/bench_runner/blob/1592e16a6921a6428a7b2812aa2e0245a806342c/bench_runner/scripts/compare.py#L157

**Comment by yuqiw4** [comment]
> Can you also update the compare script to exclude these results?
> 
> https://github.com/faster-cpython/bench_runner/blob/1592e16a6921a6428a7b2812aa2e0245a806342c/bench_runner/scripts/compare.py#L157

Sure, I just made the changes! But I'm also wondering why we need to exclude these results from cloud machines?

**Comment by mdboom** [comment]
> Sure, I just made the changes! But I'm also wondering why we need to exclude these results from cloud machines?

Because when you collect pystats, the timing results are nonsensical, so doing a comparison on those timings wouldn't make sense.

**Review by mdboom — APPROVED** [review]

**Comment by mdboom** [comment]
Thanks for the contribution!

**Pull request merged**
